name: Unit test issue82 - asfdata corrupts output
on:
  push:
    branch: main

  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        # Not sure it's worth testing on multiple Pythons
        python-version: [3.8]
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pelican[Markdown]==4.5.4
        pip install -r requirements.txt
        pip install 'MarkupSafe<2.1.0' # needed for Pelican 4.5.4
    - name: Run test
      run: |
        cd tests/issue82
        bash runtest.sh
